[package]
name = "hltb"
version = "0.1.0"
authors = ["jnskw <jonas@kowalick.org>"]
edition = "2021"

[dependencies]
argh = "0.1.4"
htmlescape = "0.3.1"
itertools = "0.10.0"
scraper = "0.12.0"
ureq = "2.0.1"
