[package]
name = "hltb"
version = "0.1.0"
authors = ["jnskw <jonas@kowalick.org>"]
edition = "2021"

[dependencies]
argh = "0.1"
serde = { version = "1.0.145", features = ["serde_derive"] }
serde_json = "1.0.87"
ureq = { version = "2.5", features = ["json"] }

